// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for PaymentInputPaymentType.
const (
	Dp         PaymentInputPaymentType = "dp"
	Settlement PaymentInputPaymentType = "settlement"
)

// Valid indicates whether the value is a known member of the PaymentInputPaymentType enum.
func (e PaymentInputPaymentType) Valid() bool {
	switch e {
	case Dp:
		return true
	case Settlement:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token *string `json:"token,omitempty"`
	User  *User   `json:"user,omitempty"`
}

// Customer defines model for Customer.
type Customer struct {
	Address   *string    `json:"address,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	IsActive  *bool      `json:"isActive,omitempty"`
	Name      *string    `json:"name,omitempty"`
	Phone     *string    `json:"phone,omitempty"`
}

// CustomerDetail defines model for CustomerDetail.
type CustomerDetail struct {
	Address   *string        `json:"address,omitempty"`
	CreatedAt *time.Time     `json:"createdAt,omitempty"`
	Id        *int64         `json:"id,omitempty"`
	IsActive  *bool          `json:"isActive,omitempty"`
	Name      *string        `json:"name,omitempty"`
	Orders    *[]interface{} `json:"orders,omitempty"`
	Phone     *string        `json:"phone,omitempty"`
}

// CustomerInput defines model for CustomerInput.
type CustomerInput struct {
	Address *string `json:"address,omitempty"`
	Name    string  `json:"name"`
	Phone   *string `json:"phone,omitempty"`
}

// ExpenditureInput defines model for ExpenditureInput.
type ExpenditureInput struct {
	Items *[]struct {
		ItemName  *string  `json:"itemName,omitempty"`
		Qty       *float32 `json:"qty,omitempty"`
		UnitPrice *float32 `json:"unitPrice,omitempty"`
	} `json:"items,omitempty"`
	Notes       *string `json:"notes,omitempty"`
	Supplier    *string `json:"supplier,omitempty"`
	TotalAmount float32 `json:"totalAmount"`
	UserId      int     `json:"userId"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// PaymentInput defines model for PaymentInput.
type PaymentInput struct {
	Amount          float32                 `json:"amount"`
	Notes           *string                 `json:"notes,omitempty"`
	PaymentMethodId int                     `json:"paymentMethodId"`
	PaymentType     PaymentInputPaymentType `json:"paymentType"`
	UserId          int                     `json:"userId"`
}

// PaymentInputPaymentType defines model for PaymentInput.PaymentType.
type PaymentInputPaymentType string

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// Service defines model for Service.
type Service struct {
	CategoryId  *int     `json:"categoryId,omitempty"`
	Description *string  `json:"description,omitempty"`
	Estimation  *string  `json:"estimation,omitempty"`
	Id          *int     `json:"id,omitempty"`
	Name        *string  `json:"name,omitempty"`
	Price       *float32 `json:"price,omitempty"`
	Unit        *string  `json:"unit,omitempty"`
}

// TransactionInput defines model for TransactionInput.
type TransactionInput struct {
	CustomerId *int  `json:"customerId,omitempty"`
	IsDelivery *bool `json:"isDelivery,omitempty"`
	Items      []struct {
		Notes     *string  `json:"notes,omitempty"`
		Qty       *float32 `json:"qty,omitempty"`
		ServiceId *int     `json:"serviceId,omitempty"`
	} `json:"items"`
	Notes  *string `json:"notes,omitempty"`
	UserId int     `json:"userId"`
}

// User defines model for User.
type User struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Email     *string    `json:"email,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	Name      *string    `json:"name,omitempty"`
}

// ListCustomersParams defines parameters for ListCustomers.
type ListCustomersParams struct {
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// ProfitLossReportParams defines parameters for ProfitLossReport.
type ProfitLossReportParams struct {
	StartDate openapi_types.Date `form:"startDate" json:"startDate"`
	EndDate   openapi_types.Date `form:"endDate" json:"endDate"`
}

// ListServicesParams defines parameters for ListServices.
type ListServicesParams struct {
	CategoryId *int `form:"categoryId,omitempty" json:"categoryId,omitempty"`
}

// ListTransactionsParams defines parameters for ListTransactions.
type ListTransactionsParams struct {
	StartDate *openapi_types.Date `form:"startDate,omitempty" json:"startDate,omitempty"`
	EndDate   *openapi_types.Date `form:"endDate,omitempty" json:"endDate,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateCustomerJSONRequestBody defines body for CreateCustomer for application/json ContentType.
type CreateCustomerJSONRequestBody = CustomerInput

// CreateExpenditureJSONRequestBody defines body for CreateExpenditure for application/json ContentType.
type CreateExpenditureJSONRequestBody = ExpenditureInput

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = TransactionInput

// AddPaymentJSONRequestBody defines body for AddPayment for application/json ContentType.
type AddPaymentJSONRequestBody = PaymentInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/login)
	Login(ctx echo.Context) error

	// (POST /auth/register)
	Register(ctx echo.Context) error

	// (GET /customers)
	ListCustomers(ctx echo.Context, params ListCustomersParams) error

	// (POST /customers)
	CreateCustomer(ctx echo.Context) error

	// (GET /customers/{id})
	GetCustomer(ctx echo.Context, id int64) error

	// (GET /dashboard)
	GetDashboard(ctx echo.Context) error

	// (POST /expenditures)
	CreateExpenditure(ctx echo.Context) error

	// (GET /payment-methods)
	ListPaymentMethods(ctx echo.Context) error

	// (GET /reports/profit-loss)
	ProfitLossReport(ctx echo.Context, params ProfitLossReportParams) error

	// (GET /service-categories)
	ListServiceCategories(ctx echo.Context) error

	// (GET /services)
	ListServices(ctx echo.Context, params ListServicesParams) error

	// (GET /transactions)
	ListTransactions(ctx echo.Context, params ListTransactionsParams) error

	// (POST /transactions)
	CreateTransaction(ctx echo.Context) error

	// (POST /transactions/{id}/payments)
	AddPayment(ctx echo.Context, id int) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Register converts echo context to params.
func (w *ServerInterfaceWrapper) Register(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Register(ctx)
	return err
}

// ListCustomers converts echo context to params.
func (w *ServerInterfaceWrapper) ListCustomers(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCustomersParams
	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", ctx.QueryParams(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListCustomers(ctx, params)
	return err
}

// CreateCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) CreateCustomer(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateCustomer(ctx)
	return err
}

// GetCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) GetCustomer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCustomer(ctx, id)
	return err
}

// GetDashboard converts echo context to params.
func (w *ServerInterfaceWrapper) GetDashboard(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDashboard(ctx)
	return err
}

// CreateExpenditure converts echo context to params.
func (w *ServerInterfaceWrapper) CreateExpenditure(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateExpenditure(ctx)
	return err
}

// ListPaymentMethods converts echo context to params.
func (w *ServerInterfaceWrapper) ListPaymentMethods(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListPaymentMethods(ctx)
	return err
}

// ProfitLossReport converts echo context to params.
func (w *ServerInterfaceWrapper) ProfitLossReport(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ProfitLossReportParams
	// ------------- Required query parameter "startDate" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "startDate", ctx.QueryParams(), &params.StartDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter startDate: %s", err))
	}

	// ------------- Required query parameter "endDate" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "endDate", ctx.QueryParams(), &params.EndDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter endDate: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ProfitLossReport(ctx, params)
	return err
}

// ListServiceCategories converts echo context to params.
func (w *ServerInterfaceWrapper) ListServiceCategories(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListServiceCategories(ctx)
	return err
}

// ListServices converts echo context to params.
func (w *ServerInterfaceWrapper) ListServices(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListServicesParams
	// ------------- Optional query parameter "categoryId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "categoryId", ctx.QueryParams(), &params.CategoryId, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter categoryId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListServices(ctx, params)
	return err
}

// ListTransactions converts echo context to params.
func (w *ServerInterfaceWrapper) ListTransactions(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTransactionsParams
	// ------------- Optional query parameter "startDate" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "startDate", ctx.QueryParams(), &params.StartDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter startDate: %s", err))
	}

	// ------------- Optional query parameter "endDate" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "endDate", ctx.QueryParams(), &params.EndDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter endDate: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListTransactions(ctx, params)
	return err
}

// CreateTransaction converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTransaction(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTransaction(ctx)
	return err
}

// AddPayment converts echo context to params.
func (w *ServerInterfaceWrapper) AddPayment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddPayment(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login, options.OperationMiddlewares["login"]...)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register, options.OperationMiddlewares["register"]...)
	router.GET(options.BaseURL+"/customers", wrapper.ListCustomers, options.OperationMiddlewares["listCustomers"]...)
	router.POST(options.BaseURL+"/customers", wrapper.CreateCustomer, options.OperationMiddlewares["createCustomer"]...)
	router.GET(options.BaseURL+"/customers/:id", wrapper.GetCustomer, options.OperationMiddlewares["getCustomer"]...)
	router.GET(options.BaseURL+"/dashboard", wrapper.GetDashboard, options.OperationMiddlewares["getDashboard"]...)
	router.POST(options.BaseURL+"/expenditures", wrapper.CreateExpenditure, options.OperationMiddlewares["createExpenditure"]...)
	router.GET(options.BaseURL+"/payment-methods", wrapper.ListPaymentMethods, options.OperationMiddlewares["listPaymentMethods"]...)
	router.GET(options.BaseURL+"/reports/profit-loss", wrapper.ProfitLossReport, options.OperationMiddlewares["profitLossReport"]...)
	router.GET(options.BaseURL+"/service-categories", wrapper.ListServiceCategories, options.OperationMiddlewares["listServiceCategories"]...)
	router.GET(options.BaseURL+"/services", wrapper.ListServices, options.OperationMiddlewares["listServices"]...)
	router.GET(options.BaseURL+"/transactions", wrapper.ListTransactions, options.OperationMiddlewares["listTransactions"]...)
	router.POST(options.BaseURL+"/transactions", wrapper.CreateTransaction, options.OperationMiddlewares["createTransaction"]...)
	router.POST(options.BaseURL+"/transactions/:id/payments", wrapper.AddPayment, options.OperationMiddlewares["addPayment"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFhRb9s2EP4rBrdHJXLWosD85ibFECxbjSx9CoyBEc82O4lUyJNXw9B/L0hKsmSRttzYfXPE4/H43Xcf",
	"77IlicxyKUCgJpMt0ckKMmp/TgtcPYLOpdBg/s6VzEEhB7uK8j8Q9scmBzIhGhUXS1JGpNCgzMKvChZk",
	"Qn6JdyfElfv4i7Epy6jeLV++QoJm922hUWbOQ/dEypgCrb1nJgooApuiWV1IlVEkE8IowhXyDEjU38JZ",
	"x5YL/PB+Z8cFwtLEGBGupwnyNbQOfpEyBSrMqqAZeEPKV1L4Vg5d+g6Q8tReNk0/L8jk+TCMDVhltI+W",
	"VAxUGyyqFN34jp+3ArgXeYGnQf8jACh4LbgCRibPbv/cA8qnbzkIxrFQEAiLI2TdH/31v0PhveKm9V0U",
	"2YtLdyE4zhRPwLPqy10X3ogIieBHShd5nnJH7d4iSqTpNJOFQH9YGtQ9ay01DN3DszLseox2WPigfpBL",
	"Lh7htQDtgRmyipT9FFOt/5eKHc+y89Ha4QtjRjcZCAyRMAxOGPPcufwLcCWZH7/G6MkubAmIIjMxs5xE",
	"RANiCma5FXJX7AalZT+QqL5P9/jGow+fR1hyjaCOZ6qRtRr3E8q2ldOMiwcQS1yRyYfo1AxH4dL+B9S6",
	"qrDuBRKKsJRqE8oUA50oniOX/rcHNPKMBpd5wG0YjIAQOJkYqO5PigpNExNVgNpJLb+B+Li+g5SvQW38",
	"j9AxIQzXR0gFtctQkNpvkMHTlczdykekL9rXKVTdwL/0hHYgLHKDG4UAi/pomU9cLKQ15piatQdaiFQu",
	"R9PZPYnIGpS2JCY31+PrsfEucxA052RC3l2Pr9/ZSsOVvW9MC1zFqRFxC4Z02mAgsbVg0HYaTxzCoPGj",
	"ZDbziRQITlapeZ4SuyP+ql0JuU7jWDvXeT/Kbh5RFWA/uE7SBvzbeHy2szttqj27IxLm3ktgI24L5f34",
	"xvjrWtyLNU05GyUKGAjkNNXGURlVwKpKdsPY1sJ8IXj3dX8Qwjc/DeE6PGAO4nEf4o+UjVQdvbH5vW/z",
	"yVTgiKYKKNuM4BvX2OShFkh7tyX46M013jZWpjgUzQDtluctMZVBXgujoHWhEg1UJSvzxjcw7Jfu/I3E",
	"bfR4YBe/36z3sP78p/vq5+GtFb7G32XY2J0VfjIXd1j1sXG3Zz3OxFvOyiBx/gBsAeajjdHZHWs4I/sX",
	"bjPo6DvxZk4NgacaJIMEMvgwqlcvkrpOLwTNXWPkjzrkHHbDmw7rpstYa9C7EGV7o+Rw1h6kWNW5X2W2",
	"qz8sTrP2AKBPhFNBLhXqOFdywfEqlTp82MzaPEitH+2ugWKIVOEdRRjGbuYse62O3zkI9mbX89MQqxrY",
	"q2qiqDrDYHaqieR2Z/1Dxw06ZODz1JqFPE/U+fRk0BtVT2yDnygDCu4Gn8PAPLUNT6brGel5EToefq1b",
	"d7+Q+vXmzzOpXzu99o2t9fCA4k8Zq4TwHI+tvxbOj2DnH1PD5xtvXVTDdX3pQqVkQmKa83h9Q8p5+T0A",
	"AP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
