// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for PaymentInputPaymentType.
const (
	Dp         PaymentInputPaymentType = "dp"
	Settlement PaymentInputPaymentType = "settlement"
)

// Valid indicates whether the value is a known member of the PaymentInputPaymentType enum.
func (e PaymentInputPaymentType) Valid() bool {
	switch e {
	case Dp:
		return true
	case Settlement:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token *string `json:"token,omitempty"`
	User  *User   `json:"user,omitempty"`
}

// Customer defines model for Customer.
type Customer struct {
	Address   *string    `json:"address,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	IsActive  *bool      `json:"isActive,omitempty"`
	Name      *string    `json:"name,omitempty"`
	Phone     *string    `json:"phone,omitempty"`
}

// CustomerDetail defines model for CustomerDetail.
type CustomerDetail struct {
	Address   *string        `json:"address,omitempty"`
	CreatedAt *time.Time     `json:"createdAt,omitempty"`
	Id        *int64         `json:"id,omitempty"`
	IsActive  *bool          `json:"isActive,omitempty"`
	Name      *string        `json:"name,omitempty"`
	Orders    *[]interface{} `json:"orders,omitempty"`
	Phone     *string        `json:"phone,omitempty"`
}

// CustomerInput defines model for CustomerInput.
type CustomerInput struct {
	Address  *string `json:"address,omitempty"`
	IsActive *bool   `json:"is_active,omitempty"`
	Name     string  `json:"name"`
	Phone    *string `json:"phone,omitempty"`
}

// DashboardResponse defines model for DashboardResponse.
type DashboardResponse struct {
	TodayExpense *float32 `json:"todayExpense,omitempty"`
	TodayIncome  *float32 `json:"todayIncome,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message *string `json:"message,omitempty"`
}

// ExpenditureInput defines model for ExpenditureInput.
type ExpenditureInput struct {
	Items       *[]ExpenditureItem `json:"items,omitempty"`
	Notes       *string            `json:"notes,omitempty"`
	Supplier    *string            `json:"supplier,omitempty"`
	TotalAmount float32            `json:"totalAmount"`
	UserId      int                `json:"userId"`
}

// ExpenditureItem defines model for ExpenditureItem.
type ExpenditureItem struct {
	ItemName  *string  `json:"itemName,omitempty"`
	Qty       *float32 `json:"qty,omitempty"`
	UnitPrice *float32 `json:"unitPrice,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// PaymentInput defines model for PaymentInput.
type PaymentInput struct {
	Amount          float32                 `json:"amount"`
	Notes           *string                 `json:"notes,omitempty"`
	PaymentMethodId int                     `json:"paymentMethodId"`
	PaymentType     PaymentInputPaymentType `json:"paymentType"`
	UserId          int                     `json:"userId"`
}

// PaymentInputPaymentType defines model for PaymentInput.PaymentType.
type PaymentInputPaymentType string

// PaymentMethod defines model for PaymentMethod.
type PaymentMethod struct {
	Id       *int    `json:"id,omitempty"`
	IsActive *bool   `json:"isActive,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// ProfitLossReport defines model for ProfitLossReport.
type ProfitLossReport struct {
	Details *[]struct {
		Date    *openapi_types.Date `json:"date,omitempty"`
		Expense *float32            `json:"expense,omitempty"`
		Income  *float32            `json:"income,omitempty"`
	} `json:"details,omitempty"`
	Profit       *float32 `json:"profit,omitempty"`
	TotalExpense *float32 `json:"totalExpense,omitempty"`
	TotalIncome  *float32 `json:"totalIncome,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// Service defines model for Service.
type Service struct {
	CategoryId  *int       `json:"categoryId,omitempty"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	Description *string    `json:"description,omitempty"`
	Estimation  *string    `json:"estimation,omitempty"`
	Id          *int       `json:"id,omitempty"`
	IsActive    *bool      `json:"isActive,omitempty"`
	MinQuantity *float32   `json:"minQuantity,omitempty"`
	Name        *string    `json:"name,omitempty"`
	Price       *float32   `json:"price,omitempty"`
	SortOrder   *int       `json:"sortOrder,omitempty"`
	Unit        *string    `json:"unit,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
}

// ServiceCategory defines model for ServiceCategory.
type ServiceCategory struct {
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          *int       `json:"id,omitempty"`
	IsActive    *bool      `json:"isActive,omitempty"`
	Name        *string    `json:"name,omitempty"`
	SortOrder   *int       `json:"sortOrder,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
}

// ServiceCategoryInput defines model for ServiceCategoryInput.
type ServiceCategoryInput struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	SortOrder   *int    `json:"sortOrder,omitempty"`
}

// ServiceDetail defines model for ServiceDetail.
type ServiceDetail struct {
	CategoryId   *int       `json:"categoryId,omitempty"`
	CategoryName *string    `json:"categoryName,omitempty"`
	CreatedAt    *time.Time `json:"createdAt,omitempty"`
	Description  *string    `json:"description,omitempty"`
	Estimation   *string    `json:"estimation,omitempty"`
	Id           *int       `json:"id,omitempty"`
	IsActive     *bool      `json:"isActive,omitempty"`
	MinQuantity  *float32   `json:"minQuantity,omitempty"`
	Name         *string    `json:"name,omitempty"`
	Price        *float32   `json:"price,omitempty"`
	Unit         *string    `json:"unit,omitempty"`
	UpdatedAt    *time.Time `json:"updatedAt,omitempty"`
}

// ServiceInput defines model for ServiceInput.
type ServiceInput struct {
	CategoryId  int      `json:"categoryId"`
	Description *string  `json:"description,omitempty"`
	Estimation  string   `json:"estimation"`
	MinQuantity *float32 `json:"minQuantity,omitempty"`
	Name        string   `json:"name"`
	Price       float32  `json:"price"`
	SortOrder   *int     `json:"sortOrder,omitempty"`
	Unit        *string  `json:"unit,omitempty"`
}

// ServiceWithCategory defines model for ServiceWithCategory.
type ServiceWithCategory struct {
	CategoryId   *int       `json:"categoryId,omitempty"`
	CategoryName *string    `json:"categoryName,omitempty"`
	CreatedAt    *time.Time `json:"createdAt,omitempty"`
	Description  *string    `json:"description,omitempty"`
	Estimation   *string    `json:"estimation,omitempty"`
	Id           *int       `json:"id,omitempty"`
	IsActive     *bool      `json:"isActive,omitempty"`
	MinQuantity  *float32   `json:"minQuantity,omitempty"`
	Name         *string    `json:"name,omitempty"`
	Price        *float32   `json:"price,omitempty"`
	SortOrder    *int       `json:"sortOrder,omitempty"`
	Unit         *string    `json:"unit,omitempty"`
	UpdatedAt    *time.Time `json:"updatedAt,omitempty"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	CustomerId      *int       `json:"customerId,omitempty"`
	Id              *int       `json:"id,omitempty"`
	InvoiceNo       *string    `json:"invoiceNo,omitempty"`
	Notes           *string    `json:"notes,omitempty"`
	PaidAmount      *float32   `json:"paidAmount,omitempty"`
	PaymentMethodId *int       `json:"paymentMethodId,omitempty"`
	PaymentStatus   *string    `json:"paymentStatus,omitempty"`
	TotalAmount     *float32   `json:"totalAmount,omitempty"`
	TransactionDate *time.Time `json:"transactionDate,omitempty"`
	UserId          *int       `json:"userId,omitempty"`
}

// TransactionInput defines model for TransactionInput.
type TransactionInput struct {
	CustomerId *int              `json:"customerId,omitempty"`
	IsDelivery *bool             `json:"isDelivery,omitempty"`
	Items      []TransactionItem `json:"items"`
	Notes      *string           `json:"notes,omitempty"`
	UserId     int               `json:"userId"`
}

// TransactionItem defines model for TransactionItem.
type TransactionItem struct {
	Notes     *string  `json:"notes,omitempty"`
	Qty       *float32 `json:"qty,omitempty"`
	ServiceId *int     `json:"serviceId,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Email     *string    `json:"email,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	Name      *string    `json:"name,omitempty"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ListCustomersParams defines parameters for ListCustomers.
type ListCustomersParams struct {
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// ProfitLossReportParams defines parameters for ProfitLossReport.
type ProfitLossReportParams struct {
	StartDate openapi_types.Date `form:"startDate" json:"startDate"`
	EndDate   openapi_types.Date `form:"endDate" json:"endDate"`
}

// ListServicesParams defines parameters for ListServices.
type ListServicesParams struct {
	// CategoryId Filter by category ID
	CategoryId *int `form:"categoryId,omitempty" json:"categoryId,omitempty"`

	// Search Search by service name
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// ListTransactionsParams defines parameters for ListTransactions.
type ListTransactionsParams struct {
	StartDate *openapi_types.Date `form:"startDate,omitempty" json:"startDate,omitempty"`
	EndDate   *openapi_types.Date `form:"endDate,omitempty" json:"endDate,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateCustomerJSONRequestBody defines body for CreateCustomer for application/json ContentType.
type CreateCustomerJSONRequestBody = CustomerInput

// UpdateCustomerJSONRequestBody defines body for UpdateCustomer for application/json ContentType.
type UpdateCustomerJSONRequestBody = CustomerInput

// CreateExpenditureJSONRequestBody defines body for CreateExpenditure for application/json ContentType.
type CreateExpenditureJSONRequestBody = ExpenditureInput

// CreateServiceCategoryJSONRequestBody defines body for CreateServiceCategory for application/json ContentType.
type CreateServiceCategoryJSONRequestBody = ServiceCategoryInput

// UpdateServiceCategoryJSONRequestBody defines body for UpdateServiceCategory for application/json ContentType.
type UpdateServiceCategoryJSONRequestBody = ServiceCategoryInput

// CreateServiceJSONRequestBody defines body for CreateService for application/json ContentType.
type CreateServiceJSONRequestBody = ServiceInput

// UpdateServiceJSONRequestBody defines body for UpdateService for application/json ContentType.
type UpdateServiceJSONRequestBody = ServiceInput

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = TransactionInput

// AddPaymentJSONRequestBody defines body for AddPayment for application/json ContentType.
type AddPaymentJSONRequestBody = PaymentInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/login)
	Login(ctx echo.Context) error

	// (POST /auth/register)
	Register(ctx echo.Context) error
	// Get all customers
	// (GET /customers)
	ListCustomers(ctx echo.Context, params ListCustomersParams) error

	// (POST /customers)
	CreateCustomer(ctx echo.Context) error

	// (DELETE /customers/{id})
	SoftDeleteCustomer(ctx echo.Context, id int64) error
	// Get customer by ID
	// (GET /customers/{id})
	GetCustomerById(ctx echo.Context, id int64) error

	// (PUT /customers/{id})
	UpdateCustomer(ctx echo.Context, id int64) error

	// (GET /dashboard)
	GetDashboard(ctx echo.Context) error

	// (POST /expenditures)
	CreateExpenditure(ctx echo.Context) error

	// (GET /health)
	Health(ctx echo.Context) error

	// (GET /payment-methods)
	ListPaymentMethods(ctx echo.Context) error

	// (GET /reports/profit-loss)
	ProfitLossReport(ctx echo.Context, params ProfitLossReportParams) error
	// Get all service categories
	// (GET /service-categories)
	ListServiceCategories(ctx echo.Context) error

	// (POST /service-categories)
	CreateServiceCategory(ctx echo.Context) error

	// (DELETE /service-categories/{id})
	SoftDeleteServiceCategory(ctx echo.Context, id int) error

	// (GET /service-categories/{id})
	GetServiceCategory(ctx echo.Context, id int) error

	// (PUT /service-categories/{id})
	UpdateServiceCategory(ctx echo.Context, id int) error
	// Get all services, can filter by category
	// (GET /services)
	ListServices(ctx echo.Context, params ListServicesParams) error
	// Create new service
	// (POST /services)
	CreateService(ctx echo.Context) error

	// (DELETE /services/{id})
	SoftDeleteService(ctx echo.Context, id int) error

	// (GET /services/{id})
	GetService(ctx echo.Context, id int) error

	// (PUT /services/{id})
	UpdateService(ctx echo.Context, id int) error

	// (GET /services/{id}/detail)
	GetServiceDetail(ctx echo.Context, id int) error

	// (GET /transactions)
	ListTransactions(ctx echo.Context, params ListTransactionsParams) error

	// (POST /transactions)
	CreateTransaction(ctx echo.Context) error

	// (POST /transactions/{id}/payments)
	AddPayment(ctx echo.Context, id int) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Register converts echo context to params.
func (w *ServerInterfaceWrapper) Register(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Register(ctx)
	return err
}

// ListCustomers converts echo context to params.
func (w *ServerInterfaceWrapper) ListCustomers(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCustomersParams
	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", ctx.QueryParams(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListCustomers(ctx, params)
	return err
}

// CreateCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) CreateCustomer(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateCustomer(ctx)
	return err
}

// SoftDeleteCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) SoftDeleteCustomer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SoftDeleteCustomer(ctx, id)
	return err
}

// GetCustomerById converts echo context to params.
func (w *ServerInterfaceWrapper) GetCustomerById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCustomerById(ctx, id)
	return err
}

// UpdateCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateCustomer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateCustomer(ctx, id)
	return err
}

// GetDashboard converts echo context to params.
func (w *ServerInterfaceWrapper) GetDashboard(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDashboard(ctx)
	return err
}

// CreateExpenditure converts echo context to params.
func (w *ServerInterfaceWrapper) CreateExpenditure(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateExpenditure(ctx)
	return err
}

// Health converts echo context to params.
func (w *ServerInterfaceWrapper) Health(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Health(ctx)
	return err
}

// ListPaymentMethods converts echo context to params.
func (w *ServerInterfaceWrapper) ListPaymentMethods(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListPaymentMethods(ctx)
	return err
}

// ProfitLossReport converts echo context to params.
func (w *ServerInterfaceWrapper) ProfitLossReport(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ProfitLossReportParams
	// ------------- Required query parameter "startDate" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "startDate", ctx.QueryParams(), &params.StartDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter startDate: %s", err))
	}

	// ------------- Required query parameter "endDate" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "endDate", ctx.QueryParams(), &params.EndDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter endDate: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ProfitLossReport(ctx, params)
	return err
}

// ListServiceCategories converts echo context to params.
func (w *ServerInterfaceWrapper) ListServiceCategories(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListServiceCategories(ctx)
	return err
}

// CreateServiceCategory converts echo context to params.
func (w *ServerInterfaceWrapper) CreateServiceCategory(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateServiceCategory(ctx)
	return err
}

// SoftDeleteServiceCategory converts echo context to params.
func (w *ServerInterfaceWrapper) SoftDeleteServiceCategory(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SoftDeleteServiceCategory(ctx, id)
	return err
}

// GetServiceCategory converts echo context to params.
func (w *ServerInterfaceWrapper) GetServiceCategory(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetServiceCategory(ctx, id)
	return err
}

// UpdateServiceCategory converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateServiceCategory(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateServiceCategory(ctx, id)
	return err
}

// ListServices converts echo context to params.
func (w *ServerInterfaceWrapper) ListServices(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListServicesParams
	// ------------- Optional query parameter "categoryId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "categoryId", ctx.QueryParams(), &params.CategoryId, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter categoryId: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", ctx.QueryParams(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListServices(ctx, params)
	return err
}

// CreateService converts echo context to params.
func (w *ServerInterfaceWrapper) CreateService(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateService(ctx)
	return err
}

// SoftDeleteService converts echo context to params.
func (w *ServerInterfaceWrapper) SoftDeleteService(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SoftDeleteService(ctx, id)
	return err
}

// GetService converts echo context to params.
func (w *ServerInterfaceWrapper) GetService(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetService(ctx, id)
	return err
}

// UpdateService converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateService(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateService(ctx, id)
	return err
}

// GetServiceDetail converts echo context to params.
func (w *ServerInterfaceWrapper) GetServiceDetail(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetServiceDetail(ctx, id)
	return err
}

// ListTransactions converts echo context to params.
func (w *ServerInterfaceWrapper) ListTransactions(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTransactionsParams
	// ------------- Optional query parameter "startDate" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "startDate", ctx.QueryParams(), &params.StartDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter startDate: %s", err))
	}

	// ------------- Optional query parameter "endDate" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "endDate", ctx.QueryParams(), &params.EndDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter endDate: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListTransactions(ctx, params)
	return err
}

// CreateTransaction converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTransaction(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTransaction(ctx)
	return err
}

// AddPayment converts echo context to params.
func (w *ServerInterfaceWrapper) AddPayment(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddPayment(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login, options.OperationMiddlewares["login"]...)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register, options.OperationMiddlewares["register"]...)
	router.GET(options.BaseURL+"/customers", wrapper.ListCustomers, options.OperationMiddlewares["listCustomers"]...)
	router.POST(options.BaseURL+"/customers", wrapper.CreateCustomer, options.OperationMiddlewares["createCustomer"]...)
	router.DELETE(options.BaseURL+"/customers/:id", wrapper.SoftDeleteCustomer, options.OperationMiddlewares["softDeleteCustomer"]...)
	router.GET(options.BaseURL+"/customers/:id", wrapper.GetCustomerById, options.OperationMiddlewares["getCustomerById"]...)
	router.PUT(options.BaseURL+"/customers/:id", wrapper.UpdateCustomer, options.OperationMiddlewares["updateCustomer"]...)
	router.GET(options.BaseURL+"/dashboard", wrapper.GetDashboard, options.OperationMiddlewares["getDashboard"]...)
	router.POST(options.BaseURL+"/expenditures", wrapper.CreateExpenditure, options.OperationMiddlewares["createExpenditure"]...)
	router.GET(options.BaseURL+"/health", wrapper.Health, options.OperationMiddlewares["health"]...)
	router.GET(options.BaseURL+"/payment-methods", wrapper.ListPaymentMethods, options.OperationMiddlewares["listPaymentMethods"]...)
	router.GET(options.BaseURL+"/reports/profit-loss", wrapper.ProfitLossReport, options.OperationMiddlewares["profitLossReport"]...)
	router.GET(options.BaseURL+"/service-categories", wrapper.ListServiceCategories, options.OperationMiddlewares["listServiceCategories"]...)
	router.POST(options.BaseURL+"/service-categories", wrapper.CreateServiceCategory, options.OperationMiddlewares["createServiceCategory"]...)
	router.DELETE(options.BaseURL+"/service-categories/:id", wrapper.SoftDeleteServiceCategory, options.OperationMiddlewares["softDeleteServiceCategory"]...)
	router.GET(options.BaseURL+"/service-categories/:id", wrapper.GetServiceCategory, options.OperationMiddlewares["getServiceCategory"]...)
	router.PUT(options.BaseURL+"/service-categories/:id", wrapper.UpdateServiceCategory, options.OperationMiddlewares["updateServiceCategory"]...)
	router.GET(options.BaseURL+"/services", wrapper.ListServices, options.OperationMiddlewares["listServices"]...)
	router.POST(options.BaseURL+"/services", wrapper.CreateService, options.OperationMiddlewares["createService"]...)
	router.DELETE(options.BaseURL+"/services/:id", wrapper.SoftDeleteService, options.OperationMiddlewares["softDeleteService"]...)
	router.GET(options.BaseURL+"/services/:id", wrapper.GetService, options.OperationMiddlewares["getService"]...)
	router.PUT(options.BaseURL+"/services/:id", wrapper.UpdateService, options.OperationMiddlewares["updateService"]...)
	router.GET(options.BaseURL+"/services/:id/detail", wrapper.GetServiceDetail, options.OperationMiddlewares["getServiceDetail"]...)
	router.GET(options.BaseURL+"/transactions", wrapper.ListTransactions, options.OperationMiddlewares["listTransactions"]...)
	router.POST(options.BaseURL+"/transactions", wrapper.CreateTransaction, options.OperationMiddlewares["createTransaction"]...)
	router.POST(options.BaseURL+"/transactions/:id/payments", wrapper.AddPayment, options.OperationMiddlewares["addPayment"]...)

}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse ErrorResponse

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201JSONResponse AuthResponse

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type Register400JSONResponse ErrorResponse

func (response Register400JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Register409JSONResponse ErrorResponse

func (response Register409JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListCustomersRequestObject struct {
	Params ListCustomersParams
}

type ListCustomersResponseObject interface {
	VisitListCustomersResponse(w http.ResponseWriter) error
}

type ListCustomers200JSONResponse []Customer

func (response ListCustomers200JSONResponse) VisitListCustomersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCustomers401JSONResponse ErrorResponse

func (response ListCustomers401JSONResponse) VisitListCustomersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCustomerRequestObject struct {
	Body *CreateCustomerJSONRequestBody
}

type CreateCustomerResponseObject interface {
	VisitCreateCustomerResponse(w http.ResponseWriter) error
}

type CreateCustomer201JSONResponse Customer

func (response CreateCustomer201JSONResponse) VisitCreateCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCustomer401Response struct {
}

func (response CreateCustomer401Response) VisitCreateCustomerResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type SoftDeleteCustomerRequestObject struct {
	Id int64 `json:"id"`
}

type SoftDeleteCustomerResponseObject interface {
	VisitSoftDeleteCustomerResponse(w http.ResponseWriter) error
}

type SoftDeleteCustomer200JSONResponse Customer

func (response SoftDeleteCustomer200JSONResponse) VisitSoftDeleteCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SoftDeleteCustomer401Response struct {
}

func (response SoftDeleteCustomer401Response) VisitSoftDeleteCustomerResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type SoftDeleteCustomer404Response struct {
}

func (response SoftDeleteCustomer404Response) VisitSoftDeleteCustomerResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetCustomerByIdRequestObject struct {
	Id int64 `json:"id"`
}

type GetCustomerByIdResponseObject interface {
	VisitGetCustomerByIdResponse(w http.ResponseWriter) error
}

type GetCustomerById200JSONResponse CustomerDetail

func (response GetCustomerById200JSONResponse) VisitGetCustomerByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCustomerById401JSONResponse ErrorResponse

func (response GetCustomerById401JSONResponse) VisitGetCustomerByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetCustomerById404JSONResponse ErrorResponse

func (response GetCustomerById404JSONResponse) VisitGetCustomerByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCustomerRequestObject struct {
	Id   int64 `json:"id"`
	Body *UpdateCustomerJSONRequestBody
}

type UpdateCustomerResponseObject interface {
	VisitUpdateCustomerResponse(w http.ResponseWriter) error
}

type UpdateCustomer200JSONResponse Customer

func (response UpdateCustomer200JSONResponse) VisitUpdateCustomerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCustomer400Response struct {
}

func (response UpdateCustomer400Response) VisitUpdateCustomerResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type UpdateCustomer401Response struct {
}

func (response UpdateCustomer401Response) VisitUpdateCustomerResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type UpdateCustomer404Response struct {
}

func (response UpdateCustomer404Response) VisitUpdateCustomerResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetDashboardRequestObject struct {
}

type GetDashboardResponseObject interface {
	VisitGetDashboardResponse(w http.ResponseWriter) error
}

type GetDashboard200JSONResponse DashboardResponse

func (response GetDashboard200JSONResponse) VisitGetDashboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDashboard401Response struct {
}

func (response GetDashboard401Response) VisitGetDashboardResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type CreateExpenditureRequestObject struct {
	Body *CreateExpenditureJSONRequestBody
}

type CreateExpenditureResponseObject interface {
	VisitCreateExpenditureResponse(w http.ResponseWriter) error
}

type CreateExpenditure201JSONResponse Transaction

func (response CreateExpenditure201JSONResponse) VisitCreateExpenditureResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateExpenditure400Response struct {
}

func (response CreateExpenditure400Response) VisitCreateExpenditureResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreateExpenditure401Response struct {
}

func (response CreateExpenditure401Response) VisitCreateExpenditureResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type HealthRequestObject struct {
}

type HealthResponseObject interface {
	VisitHealthResponse(w http.ResponseWriter) error
}

type Health200JSONResponse struct {
	Status *string `json:"status,omitempty"`
}

func (response Health200JSONResponse) VisitHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPaymentMethodsRequestObject struct {
}

type ListPaymentMethodsResponseObject interface {
	VisitListPaymentMethodsResponse(w http.ResponseWriter) error
}

type ListPaymentMethods200JSONResponse []PaymentMethod

func (response ListPaymentMethods200JSONResponse) VisitListPaymentMethodsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPaymentMethods401Response struct {
}

func (response ListPaymentMethods401Response) VisitListPaymentMethodsResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ProfitLossReportRequestObject struct {
	Params ProfitLossReportParams
}

type ProfitLossReportResponseObject interface {
	VisitProfitLossReportResponse(w http.ResponseWriter) error
}

type ProfitLossReport200JSONResponse ProfitLossReport

func (response ProfitLossReport200JSONResponse) VisitProfitLossReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ProfitLossReport401Response struct {
}

func (response ProfitLossReport401Response) VisitProfitLossReportResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ListServiceCategoriesRequestObject struct {
}

type ListServiceCategoriesResponseObject interface {
	VisitListServiceCategoriesResponse(w http.ResponseWriter) error
}

type ListServiceCategories200JSONResponse []ServiceCategory

func (response ListServiceCategories200JSONResponse) VisitListServiceCategoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListServiceCategories401Response struct {
}

func (response ListServiceCategories401Response) VisitListServiceCategoriesResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type CreateServiceCategoryRequestObject struct {
	Body *CreateServiceCategoryJSONRequestBody
}

type CreateServiceCategoryResponseObject interface {
	VisitCreateServiceCategoryResponse(w http.ResponseWriter) error
}

type CreateServiceCategory201JSONResponse ServiceCategory

func (response CreateServiceCategory201JSONResponse) VisitCreateServiceCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServiceCategory400Response struct {
}

func (response CreateServiceCategory400Response) VisitCreateServiceCategoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreateServiceCategory401Response struct {
}

func (response CreateServiceCategory401Response) VisitCreateServiceCategoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type SoftDeleteServiceCategoryRequestObject struct {
	Id int `json:"id"`
}

type SoftDeleteServiceCategoryResponseObject interface {
	VisitSoftDeleteServiceCategoryResponse(w http.ResponseWriter) error
}

type SoftDeleteServiceCategory200JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response SoftDeleteServiceCategory200JSONResponse) VisitSoftDeleteServiceCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SoftDeleteServiceCategory401Response struct {
}

func (response SoftDeleteServiceCategory401Response) VisitSoftDeleteServiceCategoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type SoftDeleteServiceCategory404Response struct {
}

func (response SoftDeleteServiceCategory404Response) VisitSoftDeleteServiceCategoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetServiceCategoryRequestObject struct {
	Id int `json:"id"`
}

type GetServiceCategoryResponseObject interface {
	VisitGetServiceCategoryResponse(w http.ResponseWriter) error
}

type GetServiceCategory200JSONResponse ServiceCategory

func (response GetServiceCategory200JSONResponse) VisitGetServiceCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetServiceCategory401Response struct {
}

func (response GetServiceCategory401Response) VisitGetServiceCategoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetServiceCategory404Response struct {
}

func (response GetServiceCategory404Response) VisitGetServiceCategoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateServiceCategoryRequestObject struct {
	Id   int `json:"id"`
	Body *UpdateServiceCategoryJSONRequestBody
}

type UpdateServiceCategoryResponseObject interface {
	VisitUpdateServiceCategoryResponse(w http.ResponseWriter) error
}

type UpdateServiceCategory200JSONResponse ServiceCategory

func (response UpdateServiceCategory200JSONResponse) VisitUpdateServiceCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateServiceCategory400Response struct {
}

func (response UpdateServiceCategory400Response) VisitUpdateServiceCategoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type UpdateServiceCategory401Response struct {
}

func (response UpdateServiceCategory401Response) VisitUpdateServiceCategoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type UpdateServiceCategory404Response struct {
}

func (response UpdateServiceCategory404Response) VisitUpdateServiceCategoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ListServicesRequestObject struct {
	Params ListServicesParams
}

type ListServicesResponseObject interface {
	VisitListServicesResponse(w http.ResponseWriter) error
}

type ListServices200JSONResponse []ServiceWithCategory

func (response ListServices200JSONResponse) VisitListServicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListServices401Response struct {
}

func (response ListServices401Response) VisitListServicesResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type CreateServiceRequestObject struct {
	Body *CreateServiceJSONRequestBody
}

type CreateServiceResponseObject interface {
	VisitCreateServiceResponse(w http.ResponseWriter) error
}

type CreateService201JSONResponse Service

func (response CreateService201JSONResponse) VisitCreateServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateService400Response struct {
}

func (response CreateService400Response) VisitCreateServiceResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreateService401Response struct {
}

func (response CreateService401Response) VisitCreateServiceResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type SoftDeleteServiceRequestObject struct {
	Id int `json:"id"`
}

type SoftDeleteServiceResponseObject interface {
	VisitSoftDeleteServiceResponse(w http.ResponseWriter) error
}

type SoftDeleteService200JSONResponse Service

func (response SoftDeleteService200JSONResponse) VisitSoftDeleteServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SoftDeleteService401Response struct {
}

func (response SoftDeleteService401Response) VisitSoftDeleteServiceResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type SoftDeleteService404Response struct {
}

func (response SoftDeleteService404Response) VisitSoftDeleteServiceResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetServiceRequestObject struct {
	Id int `json:"id"`
}

type GetServiceResponseObject interface {
	VisitGetServiceResponse(w http.ResponseWriter) error
}

type GetService200JSONResponse Service

func (response GetService200JSONResponse) VisitGetServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetService401Response struct {
}

func (response GetService401Response) VisitGetServiceResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetService404Response struct {
}

func (response GetService404Response) VisitGetServiceResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateServiceRequestObject struct {
	Id   int `json:"id"`
	Body *UpdateServiceJSONRequestBody
}

type UpdateServiceResponseObject interface {
	VisitUpdateServiceResponse(w http.ResponseWriter) error
}

type UpdateService200JSONResponse Service

func (response UpdateService200JSONResponse) VisitUpdateServiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateService400Response struct {
}

func (response UpdateService400Response) VisitUpdateServiceResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type UpdateService401Response struct {
}

func (response UpdateService401Response) VisitUpdateServiceResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type UpdateService404Response struct {
}

func (response UpdateService404Response) VisitUpdateServiceResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetServiceDetailRequestObject struct {
	Id int `json:"id"`
}

type GetServiceDetailResponseObject interface {
	VisitGetServiceDetailResponse(w http.ResponseWriter) error
}

type GetServiceDetail200JSONResponse ServiceDetail

func (response GetServiceDetail200JSONResponse) VisitGetServiceDetailResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetServiceDetail401Response struct {
}

func (response GetServiceDetail401Response) VisitGetServiceDetailResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetServiceDetail404Response struct {
}

func (response GetServiceDetail404Response) VisitGetServiceDetailResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ListTransactionsRequestObject struct {
	Params ListTransactionsParams
}

type ListTransactionsResponseObject interface {
	VisitListTransactionsResponse(w http.ResponseWriter) error
}

type ListTransactions200JSONResponse []Transaction

func (response ListTransactions200JSONResponse) VisitListTransactionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTransactions401Response struct {
}

func (response ListTransactions401Response) VisitListTransactionsResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type CreateTransactionRequestObject struct {
	Body *CreateTransactionJSONRequestBody
}

type CreateTransactionResponseObject interface {
	VisitCreateTransactionResponse(w http.ResponseWriter) error
}

type CreateTransaction201JSONResponse Transaction

func (response CreateTransaction201JSONResponse) VisitCreateTransactionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTransaction400Response struct {
}

func (response CreateTransaction400Response) VisitCreateTransactionResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreateTransaction401Response struct {
}

func (response CreateTransaction401Response) VisitCreateTransactionResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type AddPaymentRequestObject struct {
	Id   int `json:"id"`
	Body *AddPaymentJSONRequestBody
}

type AddPaymentResponseObject interface {
	VisitAddPaymentResponse(w http.ResponseWriter) error
}

type AddPayment200JSONResponse Transaction

func (response AddPayment200JSONResponse) VisitAddPaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AddPayment400Response struct {
}

func (response AddPayment400Response) VisitAddPaymentResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type AddPayment401Response struct {
}

func (response AddPayment401Response) VisitAddPaymentResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)

	// (POST /auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// Get all customers
	// (GET /customers)
	ListCustomers(ctx context.Context, request ListCustomersRequestObject) (ListCustomersResponseObject, error)

	// (POST /customers)
	CreateCustomer(ctx context.Context, request CreateCustomerRequestObject) (CreateCustomerResponseObject, error)

	// (DELETE /customers/{id})
	SoftDeleteCustomer(ctx context.Context, request SoftDeleteCustomerRequestObject) (SoftDeleteCustomerResponseObject, error)
	// Get customer by ID
	// (GET /customers/{id})
	GetCustomerById(ctx context.Context, request GetCustomerByIdRequestObject) (GetCustomerByIdResponseObject, error)

	// (PUT /customers/{id})
	UpdateCustomer(ctx context.Context, request UpdateCustomerRequestObject) (UpdateCustomerResponseObject, error)

	// (GET /dashboard)
	GetDashboard(ctx context.Context, request GetDashboardRequestObject) (GetDashboardResponseObject, error)

	// (POST /expenditures)
	CreateExpenditure(ctx context.Context, request CreateExpenditureRequestObject) (CreateExpenditureResponseObject, error)

	// (GET /health)
	Health(ctx context.Context, request HealthRequestObject) (HealthResponseObject, error)

	// (GET /payment-methods)
	ListPaymentMethods(ctx context.Context, request ListPaymentMethodsRequestObject) (ListPaymentMethodsResponseObject, error)

	// (GET /reports/profit-loss)
	ProfitLossReport(ctx context.Context, request ProfitLossReportRequestObject) (ProfitLossReportResponseObject, error)
	// Get all service categories
	// (GET /service-categories)
	ListServiceCategories(ctx context.Context, request ListServiceCategoriesRequestObject) (ListServiceCategoriesResponseObject, error)

	// (POST /service-categories)
	CreateServiceCategory(ctx context.Context, request CreateServiceCategoryRequestObject) (CreateServiceCategoryResponseObject, error)

	// (DELETE /service-categories/{id})
	SoftDeleteServiceCategory(ctx context.Context, request SoftDeleteServiceCategoryRequestObject) (SoftDeleteServiceCategoryResponseObject, error)

	// (GET /service-categories/{id})
	GetServiceCategory(ctx context.Context, request GetServiceCategoryRequestObject) (GetServiceCategoryResponseObject, error)

	// (PUT /service-categories/{id})
	UpdateServiceCategory(ctx context.Context, request UpdateServiceCategoryRequestObject) (UpdateServiceCategoryResponseObject, error)
	// Get all services, can filter by category
	// (GET /services)
	ListServices(ctx context.Context, request ListServicesRequestObject) (ListServicesResponseObject, error)
	// Create new service
	// (POST /services)
	CreateService(ctx context.Context, request CreateServiceRequestObject) (CreateServiceResponseObject, error)

	// (DELETE /services/{id})
	SoftDeleteService(ctx context.Context, request SoftDeleteServiceRequestObject) (SoftDeleteServiceResponseObject, error)

	// (GET /services/{id})
	GetService(ctx context.Context, request GetServiceRequestObject) (GetServiceResponseObject, error)

	// (PUT /services/{id})
	UpdateService(ctx context.Context, request UpdateServiceRequestObject) (UpdateServiceResponseObject, error)

	// (GET /services/{id}/detail)
	GetServiceDetail(ctx context.Context, request GetServiceDetailRequestObject) (GetServiceDetailResponseObject, error)

	// (GET /transactions)
	ListTransactions(ctx context.Context, request ListTransactionsRequestObject) (ListTransactionsResponseObject, error)

	// (POST /transactions)
	CreateTransaction(ctx context.Context, request CreateTransactionRequestObject) (CreateTransactionResponseObject, error)

	// (POST /transactions/{id}/payments)
	AddPayment(ctx context.Context, request AddPaymentRequestObject) (AddPaymentResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Login operation middleware
func (sh *strictHandler) Login(ctx echo.Context) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Register operation middleware
func (sh *strictHandler) Register(ctx echo.Context) error {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx.Request().Context(), request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		return validResponse.VisitRegisterResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListCustomers operation middleware
func (sh *strictHandler) ListCustomers(ctx echo.Context, params ListCustomersParams) error {
	var request ListCustomersRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListCustomers(ctx.Request().Context(), request.(ListCustomersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCustomers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListCustomersResponseObject); ok {
		return validResponse.VisitListCustomersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateCustomer operation middleware
func (sh *strictHandler) CreateCustomer(ctx echo.Context) error {
	var request CreateCustomerRequestObject

	var body CreateCustomerJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCustomer(ctx.Request().Context(), request.(CreateCustomerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCustomer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateCustomerResponseObject); ok {
		return validResponse.VisitCreateCustomerResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SoftDeleteCustomer operation middleware
func (sh *strictHandler) SoftDeleteCustomer(ctx echo.Context, id int64) error {
	var request SoftDeleteCustomerRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SoftDeleteCustomer(ctx.Request().Context(), request.(SoftDeleteCustomerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SoftDeleteCustomer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SoftDeleteCustomerResponseObject); ok {
		return validResponse.VisitSoftDeleteCustomerResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCustomerById operation middleware
func (sh *strictHandler) GetCustomerById(ctx echo.Context, id int64) error {
	var request GetCustomerByIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCustomerById(ctx.Request().Context(), request.(GetCustomerByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCustomerById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCustomerByIdResponseObject); ok {
		return validResponse.VisitGetCustomerByIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateCustomer operation middleware
func (sh *strictHandler) UpdateCustomer(ctx echo.Context, id int64) error {
	var request UpdateCustomerRequestObject

	request.Id = id

	var body UpdateCustomerJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCustomer(ctx.Request().Context(), request.(UpdateCustomerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCustomer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateCustomerResponseObject); ok {
		return validResponse.VisitUpdateCustomerResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetDashboard operation middleware
func (sh *strictHandler) GetDashboard(ctx echo.Context) error {
	var request GetDashboardRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDashboard(ctx.Request().Context(), request.(GetDashboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDashboard")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetDashboardResponseObject); ok {
		return validResponse.VisitGetDashboardResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateExpenditure operation middleware
func (sh *strictHandler) CreateExpenditure(ctx echo.Context) error {
	var request CreateExpenditureRequestObject

	var body CreateExpenditureJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateExpenditure(ctx.Request().Context(), request.(CreateExpenditureRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateExpenditure")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateExpenditureResponseObject); ok {
		return validResponse.VisitCreateExpenditureResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Health operation middleware
func (sh *strictHandler) Health(ctx echo.Context) error {
	var request HealthRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Health(ctx.Request().Context(), request.(HealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Health")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(HealthResponseObject); ok {
		return validResponse.VisitHealthResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListPaymentMethods operation middleware
func (sh *strictHandler) ListPaymentMethods(ctx echo.Context) error {
	var request ListPaymentMethodsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListPaymentMethods(ctx.Request().Context(), request.(ListPaymentMethodsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPaymentMethods")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListPaymentMethodsResponseObject); ok {
		return validResponse.VisitListPaymentMethodsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ProfitLossReport operation middleware
func (sh *strictHandler) ProfitLossReport(ctx echo.Context, params ProfitLossReportParams) error {
	var request ProfitLossReportRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ProfitLossReport(ctx.Request().Context(), request.(ProfitLossReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProfitLossReport")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ProfitLossReportResponseObject); ok {
		return validResponse.VisitProfitLossReportResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListServiceCategories operation middleware
func (sh *strictHandler) ListServiceCategories(ctx echo.Context) error {
	var request ListServiceCategoriesRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListServiceCategories(ctx.Request().Context(), request.(ListServiceCategoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListServiceCategories")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListServiceCategoriesResponseObject); ok {
		return validResponse.VisitListServiceCategoriesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateServiceCategory operation middleware
func (sh *strictHandler) CreateServiceCategory(ctx echo.Context) error {
	var request CreateServiceCategoryRequestObject

	var body CreateServiceCategoryJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateServiceCategory(ctx.Request().Context(), request.(CreateServiceCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateServiceCategory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateServiceCategoryResponseObject); ok {
		return validResponse.VisitCreateServiceCategoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SoftDeleteServiceCategory operation middleware
func (sh *strictHandler) SoftDeleteServiceCategory(ctx echo.Context, id int) error {
	var request SoftDeleteServiceCategoryRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SoftDeleteServiceCategory(ctx.Request().Context(), request.(SoftDeleteServiceCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SoftDeleteServiceCategory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SoftDeleteServiceCategoryResponseObject); ok {
		return validResponse.VisitSoftDeleteServiceCategoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetServiceCategory operation middleware
func (sh *strictHandler) GetServiceCategory(ctx echo.Context, id int) error {
	var request GetServiceCategoryRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetServiceCategory(ctx.Request().Context(), request.(GetServiceCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetServiceCategory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetServiceCategoryResponseObject); ok {
		return validResponse.VisitGetServiceCategoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateServiceCategory operation middleware
func (sh *strictHandler) UpdateServiceCategory(ctx echo.Context, id int) error {
	var request UpdateServiceCategoryRequestObject

	request.Id = id

	var body UpdateServiceCategoryJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateServiceCategory(ctx.Request().Context(), request.(UpdateServiceCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateServiceCategory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateServiceCategoryResponseObject); ok {
		return validResponse.VisitUpdateServiceCategoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListServices operation middleware
func (sh *strictHandler) ListServices(ctx echo.Context, params ListServicesParams) error {
	var request ListServicesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListServices(ctx.Request().Context(), request.(ListServicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListServices")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListServicesResponseObject); ok {
		return validResponse.VisitListServicesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateService operation middleware
func (sh *strictHandler) CreateService(ctx echo.Context) error {
	var request CreateServiceRequestObject

	var body CreateServiceJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateService(ctx.Request().Context(), request.(CreateServiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateService")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateServiceResponseObject); ok {
		return validResponse.VisitCreateServiceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SoftDeleteService operation middleware
func (sh *strictHandler) SoftDeleteService(ctx echo.Context, id int) error {
	var request SoftDeleteServiceRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SoftDeleteService(ctx.Request().Context(), request.(SoftDeleteServiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SoftDeleteService")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SoftDeleteServiceResponseObject); ok {
		return validResponse.VisitSoftDeleteServiceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetService operation middleware
func (sh *strictHandler) GetService(ctx echo.Context, id int) error {
	var request GetServiceRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetService(ctx.Request().Context(), request.(GetServiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetService")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetServiceResponseObject); ok {
		return validResponse.VisitGetServiceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateService operation middleware
func (sh *strictHandler) UpdateService(ctx echo.Context, id int) error {
	var request UpdateServiceRequestObject

	request.Id = id

	var body UpdateServiceJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateService(ctx.Request().Context(), request.(UpdateServiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateService")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateServiceResponseObject); ok {
		return validResponse.VisitUpdateServiceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetServiceDetail operation middleware
func (sh *strictHandler) GetServiceDetail(ctx echo.Context, id int) error {
	var request GetServiceDetailRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetServiceDetail(ctx.Request().Context(), request.(GetServiceDetailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetServiceDetail")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetServiceDetailResponseObject); ok {
		return validResponse.VisitGetServiceDetailResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListTransactions operation middleware
func (sh *strictHandler) ListTransactions(ctx echo.Context, params ListTransactionsParams) error {
	var request ListTransactionsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListTransactions(ctx.Request().Context(), request.(ListTransactionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTransactions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListTransactionsResponseObject); ok {
		return validResponse.VisitListTransactionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateTransaction operation middleware
func (sh *strictHandler) CreateTransaction(ctx echo.Context) error {
	var request CreateTransactionRequestObject

	var body CreateTransactionJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTransaction(ctx.Request().Context(), request.(CreateTransactionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTransaction")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateTransactionResponseObject); ok {
		return validResponse.VisitCreateTransactionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AddPayment operation middleware
func (sh *strictHandler) AddPayment(ctx echo.Context, id int) error {
	var request AddPaymentRequestObject

	request.Id = id

	var body AddPaymentJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AddPayment(ctx.Request().Context(), request.(AddPaymentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddPayment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AddPaymentResponseObject); ok {
		return validResponse.VisitAddPaymentResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fvdctu4FX4VDdpLJrK7mZ2p7hx7N3WbOmkcz154PDswcSRhlwRo4NBb1aN37wAgJZIC+GNJjL27d1YA",
	"Agffd/6BPJFYppkUIFCT2RPR8RJSav88y3H5BXQmhQbzO1MyA4Uc7CjKX0HYP1YZkBnRqLhYkHVEcg3K",
	"DPxVwZzMyF+m2x2mxfLTGzNnvY7Kr+X9LxCj+fo81yhTt0J9R8qYAq29e8YKKAI7QzM6lyqlSGaEUYQ3",
	"yFMg0e4nnNXmcoHfv9vO4wJhYWSMCNdnMfJHqGx8L2UCVJhRQVPwipQtpfCNtB36ApDyxB42ST7Nyey2",
	"HcYNWOuoiZZUDFQVLKoUXfm2v6sIcCmyHIdBz/XP9MD4KHjIuQJGZrfu+zsPZhdUL+8lVaxNRxld/fDf",
	"DIrRYg2Rp/eOWjvhUsQy9Y37mPpBKanCO6agNV30pd2KxjjmCgLAc4S0/kebOlTXQ0jJds+C/IgIieDn",
	"UedZlnBneDuDKJEmZ6nMBXqBNDZ/ySpDG/tp0FlMrK8Y2eNdhZhuHsuL0lVIzx5w5RdZcPyseNyX+Y9y",
	"wcUXeMhBe4iCtDDcXT2nWv8mFetWdbdG5QsfGJ/pKgWBIUMNUxRmPnNL/htwKZmfxc2kr3bgiYDIUyMz",
	"y0hENCAmYIYrItcDQi/laAoSleepb79ZsQUft4ZHVQLHe5aT96nJZyXnHD9Krb9AJpWHI2adfN2qGzMo",
	"wk4g88UwaPFtfIhba7qJzJ4i4DORJu1OFWkyyKl+gQXXCKrbujaIlLayA0k43lTsMOXiI4gFLsns+2io",
	"VUbhmHQN6rHwKPUDxBRhIdUqZF3PyF8Y6FjxDLn0p2Ggkac0OPw8Q0i5+E9OBfKAUw2jH/C0EdFS4SeT",
	"rPjlMW7an2ZmbBhk6zBh5wU9HuIOT8xBXVA3fkeAKRB8ug7+vCP0zQcLGbcp9EALLMaDecQf2ERHscGA",
	"UnXxtifGDbQYzGmeIJmdRmM6t8225NcF6QpIFUQKmUoJaqdtsZGfOC5bXN6flvI6g9lXRYU2tbhDqcFq",
	"WeGHoAr9u3iUPIYr6XfpLUUFZy0F45Ca4xop5vpZdSluIbnwJdVBhWytWdqQD7mxLvj1BST8EdTKr6vD",
	"GgFVeQY3AobX8k6muw5gvKV7WIxQ3a6LcNGbnBvt6yYWTupnOsBLhYv83s3E3pWkPWmcK46ra8Oqk/o9",
	"UAXqLDeVyxO5t79+LHf9509fTTFuZxvtsaNbKZaIGVmvrU3PnTlzTMzIR5qLRC4mZ58vSUQeQWnrQsjp",
	"25O3J0ZqmYGgGScz8t3bk7ff2WoIl1aiKc1xOU3kgjunI139ZqC2/trw5HonxGkPaHwvmeU2lgLBWS7N",
	"soTH9ovpL9o5MKfNXbpe68us6zqKKgf7D65fZwX+28nJwfautcjt3rVAZs69ADbh1oTfnZwebON6G9Kz",
	"86V4pAlnk1gBA4GcJrqmU2R2e2d+O/pUUYCHGSxL9COR2OwA9OLxdDQeS/GAOSJPxiPyPWUTVaJi9v77",
	"eHufSzFPeMMbbTSnDGmWjQX4zJ5rPN/MMk5D0RTQfnL7RIzHIA+5iXmlYyQaqIqXpRujPld5t6dB94qg",
	"lZuV5gXKDkyf/jW6ed8IY7dS8f8ZlbTd+zSlJnkgHwAnNEkmW3pMJuU16nMbAzdHPY5p16+WRjbsLY0e",
	"7XYZQIW7VozrOj994mztvknAJZZ1bK/lHC/sWAVfnwGYSLrVf85IE5+qLXRmGHtbx3PRNOedODDYROdx",
	"DFrP8yRZ9cTXTHq3O6ncciIkTuYyF8xt7vU3H2Djbt678vh3AnjR1HqJvmfD2zibX1XUoOn1SuOc3K8m",
	"lxfW7eUeLbmxtfY3sMoX4VvH8QYO42q21JHVHNY/GFfNyvcBwfTkA+DmEQE5IlC7LxW6DLk7EMH2TlyH",
	"s3YX4ir350eK8TsPGUYO89XOV1ekP4g2OhKWQBNXiXv16x9ueE/NqrctdKgX5ukgeHXMl8kXfbY3qe3G",
	"tefztft1TcbIxetX+kMT8m4alb2o11N36f0mkToMwc71fr+qBqnCC3eJ3yOM+K/715F/cRBs76WPmcTs",
	"QLY/Y0UP8E1xFVHYRlBn69eXZvYYatu8Wz6o4voqvgKVSQWVjtKvKeJxooP39njkCLFDxnhRYldZBxSP",
	"uwztna0evIJ5/hPI9jJyv8zwql/B+BoA3lOxe3uVfki2FFWjgfmSnNSoXI5WWF0166nCjfWKtJ5mb331",
	"H3mCrlAvXxOYij3y5je19w4tihE1N7m2vWSzSRkZi9cSL7nx7HuiMVbmoKNJTMVkvkNOzzziuPnDt8wb",
	"RsoXqty45ScCfivpITU7HJ5EvNbY9pLyhN8ThqPnBa8wH/iWecDLjP/W70zZ5plth8EUVxev1Gx6Xrwc",
	"At/KU7X2HOtrdeLg9tMB203jtZeGPno7cJOwPfmp7nscX7TzvPCP0V6vWoTzOkWjuuXG44yxol38moJN",
	"7T/1jRxsOsgtzeRQvNbvH+ovGm/vDMAm0JSU5SohMzKlGZ8+npL13fr/AQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
