// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresql

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BlacklistedToken struct {
	Jti       string             `json:"jti"`
	ExpiresAt time.Time          `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Customer struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	Phone     pgtype.Text `json:"phone"`
	Address   pgtype.Text `json:"address"`
	IsActive  bool        `json:"is_active"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type Menu struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	Url        pgtype.Text `json:"url"`
	Icon       pgtype.Text `json:"icon"`
	ParentID   pgtype.Int8 `json:"parent_id"`
	SortOrder  int32       `json:"sort_order"`
	IsActive   bool        `json:"is_active"`
	AssignedAt time.Time   `json:"assigned_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type PaymentMethod struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	IsActive  bool      `json:"is_active"`
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Role struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type RoleMenu struct {
	ID         int64     `json:"id"`
	RoleID     int64     `json:"role_id"`
	MenuID     int64     `json:"menu_id"`
	CanView    bool      `json:"can_view"`
	CanCreate  bool      `json:"can_create"`
	CanEdit    bool      `json:"can_edit"`
	CanDelete  bool      `json:"can_delete"`
	AssignedAt time.Time `json:"assigned_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Service struct {
	ID          int64          `json:"id"`
	CategoryID  int64          `json:"category_id"`
	Name        string         `json:"name"`
	Price       pgtype.Numeric `json:"price"`
	Estimation  string         `json:"estimation"`
	MinQuantity pgtype.Numeric `json:"min_quantity"`
	Unit        string         `json:"unit"`
	Description pgtype.Text    `json:"description"`
	IsActive    bool           `json:"is_active"`
	SortOrder   int32          `json:"sort_order"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type ServiceCategory struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	SortOrder   int32       `json:"sort_order"`
	UpdatedAt   time.Time   `json:"updated_at"`
	CreatedAt   time.Time   `json:"created_at"`
}

type Transaction struct {
	ID              int64              `json:"id"`
	InvoiceNo       string             `json:"invoice_no"`
	TransactionType string             `json:"transaction_type"`
	UserID          int64              `json:"user_id"`
	CustomerID      pgtype.Int8        `json:"customer_id"`
	PaymentMethodID pgtype.Int8        `json:"payment_method_id"`
	PaymentStatus   string             `json:"payment_status"`
	IsDelivery      bool               `json:"is_delivery"`
	Supplier        pgtype.Text        `json:"supplier"`
	ExpenseCategory pgtype.Text        `json:"expense_category"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	PaidAmount      pgtype.Numeric     `json:"paid_amount"`
	Notes           pgtype.Text        `json:"notes"`
	TransactionDate time.Time          `json:"transaction_date"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	IsDeleted       pgtype.Bool        `json:"is_deleted"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type TransactionDelivery struct {
	ID            int64              `json:"id"`
	TransactionID int64              `json:"transaction_id"`
	TdType        string             `json:"td_type"`
	Status        string             `json:"status"`
	Address       string             `json:"address"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CourierName   pgtype.Text        `json:"courier_name"`
	DeliveryFee   pgtype.Numeric     `json:"delivery_fee"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type TransactionItem struct {
	ID            int64          `json:"id"`
	TransactionID int64          `json:"transaction_id"`
	ServiceID     pgtype.Int8    `json:"service_id"`
	ItemName      pgtype.Text    `json:"item_name"`
	Qty           pgtype.Numeric `json:"qty"`
	Unit          pgtype.Text    `json:"unit"`
	UnitPrice     pgtype.Numeric `json:"unit_price"`
	Subtotal      pgtype.Numeric `json:"subtotal"`
	Notes         pgtype.Text    `json:"notes"`
}

type TransactionPayment struct {
	ID              int64          `json:"id"`
	TransactionID   int64          `json:"transaction_id"`
	PaymentMethodID int64          `json:"payment_method_id"`
	Amount          pgtype.Numeric `json:"amount"`
	PaymentType     string         `json:"payment_type"`
	PaidAt          time.Time      `json:"paid_at"`
	ReceivedBy      int64          `json:"received_by"`
	Notes           pgtype.Text    `json:"notes"`
	CreatedAt       time.Time      `json:"created_at"`
}

type User struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	PasswordHash string      `json:"password_hash"`
	RoleID       int64       `json:"role_id"`
	IsActive     bool        `json:"is_active"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}
