// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgresql

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (name, phone, address)
VALUES ($1, $2, $3)
    RETURNING id, name, phone, address, is_active, created_at, updated_at
`

type CreateCustomerParams struct {
	Name    string      `json:"name"`
	Phone   pgtype.Text `json:"phone"`
	Address pgtype.Text `json:"address"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.Name, arg.Phone, arg.Address)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (invoice_no, type, user_id, customer_id, payment_status, is_delivery, total_amount, notes)
VALUES ($1, 'income', $2, $3, 'unpaid', $4, $5, $6)
    RETURNING id, invoice_no, type, user_id, customer_id, payment_method_id, payment_status, is_delivery, paid_amount, supplier, total_amount, notes, transaction_date, created_at, updated_at
`

type CreateTransactionParams struct {
	InvoiceNo   string         `json:"invoice_no"`
	UserID      int64          `json:"user_id"`
	CustomerID  pgtype.Int8    `json:"customer_id"`
	IsDelivery  bool           `json:"is_delivery"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
	Notes       pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.InvoiceNo,
		arg.UserID,
		arg.CustomerID,
		arg.IsDelivery,
		arg.TotalAmount,
		arg.Notes,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.Type,
		&i.UserID,
		&i.CustomerID,
		&i.PaymentMethodID,
		&i.PaymentStatus,
		&i.IsDelivery,
		&i.PaidAmount,
		&i.Supplier,
		&i.TotalAmount,
		&i.Notes,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransactionItem = `-- name: CreateTransactionItem :one
INSERT INTO transaction_items (transaction_id, service_id, qty, unit, unit_price, notes)
SELECT $1, $2, $3, s.unit, s.price, $4
FROM services s WHERE s.id = $2
    RETURNING id, transaction_id, service_id, item_name, qty, unit, unit_price, subtotal, notes
`

type CreateTransactionItemParams struct {
	TransactionID int64          `json:"transaction_id"`
	ServiceID     pgtype.Int8    `json:"service_id"`
	Qty           pgtype.Numeric `json:"qty"`
	Notes         pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateTransactionItem(ctx context.Context, arg CreateTransactionItemParams) (TransactionItem, error) {
	row := q.db.QueryRow(ctx, createTransactionItem,
		arg.TransactionID,
		arg.ServiceID,
		arg.Qty,
		arg.Notes,
	)
	var i TransactionItem
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ServiceID,
		&i.ItemName,
		&i.Qty,
		&i.Unit,
		&i.UnitPrice,
		&i.Subtotal,
		&i.Notes,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, role_id, is_active)
VALUES ($1, $2, $3, (SELECT id FROM roles WHERE name = 'kasir' LIMIT 1), true)
RETURNING id, name, email, created_at
`

type CreateUserParams struct {
	Name         pgtype.Text `json:"name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
}

type CreateUserRow struct {
	ID        int64       `json:"id"`
	Name      pgtype.Text `json:"name"`
	Email     string      `json:"email"`
	CreatedAt time.Time   `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerById = `-- name: GetCustomerById :one
SELECT id, name, phone, address, is_active, created_at, updated_at FROM customers WHERE id = $1
`

func (q *Queries) GetCustomerById(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerById, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceById = `-- name: GetServiceById :one
SELECT id, category_id, name, price, estimation, min_quantity, unit, description, is_active, sort_order, created_at, updated_at FROM services WHERE id = $1
`

func (q *Queries) GetServiceById(ctx context.Context, id int64) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceById, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Price,
		&i.Estimation,
		&i.MinQuantity,
		&i.Unit,
		&i.Description,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodayIncomeExpense = `-- name: GetTodayIncomeExpense :one
SELECT
    COALESCE(SUM(CASE WHEN type='income' THEN total_amount ELSE 0 END),0) as today_income,
    COALESCE(SUM(CASE WHEN type='expenditure' THEN total_amount ELSE 0 END),0) as today_expense
FROM transactions
WHERE DATE(transaction_date) = CURRENT_DATE
`

type GetTodayIncomeExpenseRow struct {
	TodayIncome  interface{} `json:"today_income"`
	TodayExpense interface{} `json:"today_expense"`
}

func (q *Queries) GetTodayIncomeExpense(ctx context.Context) (GetTodayIncomeExpenseRow, error) {
	row := q.db.QueryRow(ctx, getTodayIncomeExpense)
	var i GetTodayIncomeExpenseRow
	err := row.Scan(&i.TodayIncome, &i.TodayExpense)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, role_id, is_active, created_at
FROM users
WHERE email = $1 AND is_active = true
`

type GetUserByEmailRow struct {
	ID           int64       `json:"id"`
	Name         pgtype.Text `json:"name"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	RoleID       int64       `json:"role_id"`
	IsActive     bool        `json:"is_active"`
	CreatedAt    time.Time   `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, name, phone, address, is_active, created_at, updated_at FROM customers
WHERE ($1::text = '' OR name ILIKE '%' || $1 || '%' OR phone ILIKE '%' || $1 || '%')
ORDER BY name
`

func (q *Queries) ListCustomers(ctx context.Context, dollar_1 string) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Address,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
