// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresql

import (
	"context"
)

type Querier interface {
	// ==================== BLACKLIST TOKENS ====================
	AddTokenToBlacklist(ctx context.Context, arg AddTokenToBlacklistParams) error
	// ==================== CUSTOMERS ====================
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	// ==================== SERVICES ====================
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	// ==================== SERVICE CATEGORIES ====================
	CreateServiceCategory(ctx context.Context, arg CreateServiceCategoryParams) (ServiceCategory, error)
	// ==================== TRANSACTIONS ====================
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTransactionItem(ctx context.Context, arg CreateTransactionItemParams) (TransactionItem, error)
	// ==================== AUTH & USERS ====================
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetCustomerById(ctx context.Context, id int64) (Customer, error)
	GetServiceByID(ctx context.Context, id int64) (GetServiceByIDRow, error)
	GetServiceCategoryByID(ctx context.Context, id int64) (GetServiceCategoryByIDRow, error)
	GetServiceDetail(ctx context.Context, id int64) (GetServiceDetailRow, error)
	GetTodayIncomeExpense(ctx context.Context) (GetTodayIncomeExpenseRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	IsTokenBlacklisted(ctx context.Context, jti string) (bool, error)
	ListCustomers(ctx context.Context, dollar_1 string) ([]Customer, error)
	ListServiceCategories(ctx context.Context) ([]ListServiceCategoriesRow, error)
	ListServices(ctx context.Context) ([]ListServicesRow, error)
	SoftDeleteCustomer(ctx context.Context, id int64) (Customer, error)
	SoftDeleteService(ctx context.Context, id int64) (Service, error)
	SoftDeleteServiceCategory(ctx context.Context, id int64) (ServiceCategory, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	UpdateServiceCategory(ctx context.Context, arg UpdateServiceCategoryParams) (ServiceCategory, error)
}

var _ Querier = (*Queries)(nil)
