// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresql

import (
	"context"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTransactionItem(ctx context.Context, arg CreateTransactionItemParams) (TransactionItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetCustomerById(ctx context.Context, id int64) (Customer, error)
	GetServiceById(ctx context.Context, id int64) (Service, error)
	GetTodayIncomeExpense(ctx context.Context) (GetTodayIncomeExpenseRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	ListCustomers(ctx context.Context, dollar_1 string) ([]Customer, error)
}

var _ Querier = (*Queries)(nil)
